### ISSUE TITLE
Spraviť porovnanie SK a CZ databáz

### ISSUE THREAD

**Issue by Matoo125** [Matoo125/Vegapo#18]
Verejná stránka dostupná cez footer odkaz, kde sa porovnaná obsah SK a CZ databáz. Môže to fungovať, ako motivátor pre užívateľov. 

Mala by to byť pekná štatistická stránka s grafmi a obrátzkami.

Porovnať počet
+ produktov
+ užívateľov
+ pripomienok
+ správ

Pridať aj graf zobrazujúci aktivitu naprieč časom.

**Comment by Matoo125** [comment]
http://www.chartjs.org

Určite by som použil ChartJS na grafy.

**Comment by mrkovec** [comment]
@Matoo125 je tato uloha este stale "help wanted", alebo si uz na nej zacal robit?

**Comment by Matoo125** [comment]
momentálne nerobím nič. Keď začnem dám si assignee

**Comment by Matoo125** [comment]
Ak maš čas a vôľu, priraď si issue a je to len tvoje

**Comment by Matoo125** [comment]
Keď dokončíme tieto 2 tasky asi by som to aj zverejnil
