### ISSUE TITLE
logovanie Editov

### ISSUE THREAD

**Issue by Matoo125** [Matoo125/Vegapo#25]
Všetky zmeny, ako 
- [x] schvalovanie produktov
- [x] upravovanie produktov
- [x] schvalovanie návhrov (suggestions)
- [x] upravovanie jazykových súborov
- [ ] posielanie newsletteru (toto nieje edit ale pre jednoduchosť to necháme tu)
- [ ] menenie práv

by mali byť zalogované.

V #22 sa otvorila diskusia a @mrkovec už spravil základy pre logovanie editov.

**Comment by mrkovec** [comment]
Pustim sa do napasovania editov na uz existujucu admin funkcionalitu ziadosti a pripomienok.
