### ISSUE TITLE
Filtrovanie produktov na zaklade viacerych tagov.

### ISSUE THREAD

**Issue by mrkovec** [Matoo125/Vegapo#4]
Pridanie moznosti filtrovat produkty na zaklade viacerych roznych tagov - pridavanie a odoberanie tagov z filtra.

**Comment by Matoo125** [comment]
Ahoj, v prvom rade by som chcel pochváliť super spracovanie! 👍 

Mám iba dve otázky k tomu SQL

Nepochopil som úplne tej poznámke 

> nechcel som zasiahnut do hodnot vracanych funkciou getProducts

Ako sa nedá zasahovať do hodnôť keď píšeš WHERE slučku?

A ešte by ma zaujímalo, či ten tvoj sql má nejakú výhodu nad
```php
$tag_slugs = "'" . implode("', '", $tag_slugs)  . "'";
$where[]  ="t.slug IN(:tag_slugs)";
$array['tags'] = $tag_slugs;
```

Možno sa odpoveď na moju druhú otázku nachádza v prvej ... v každom prípade ďakujem za spoluprácu a toto už je iba taký estetický dodatok. :) 💯

**Comment by mrkovec** [comment]
Slo mi o to, ze v query (vo fnc getProducts) sa selectuju concatnute mena tagov pre konkretny produkt (app/model/Product.php riadok 154 `GROUP_CONCAT(DISTINCT t.name) AS tags`) a ked som where podmienku skusal spravit podobne ako pises, tak ten zoznam tagov obsahoval len tie, ktore boli v podmienke. Neviem, ci sa vyjadrujem jasne - chcel som dosiahnut aby produkt mal uvedene vsetky tagy, ktore su k nemu pridelene, nie len tie za zaklade ktorych je selectovany. 
Mozno je to bezpredmetne a `tags` stlpec nemusi obsahovat vsetky produktove tagy - v tom pripade je tvoje riesenie idealne.

**Comment by Matoo125** [comment]
Aha už som pochopil.

Ja som zabudol, že sa tam selektuje aj zoznam tagov, pretože najprv som spravil query a potom som to nikde nezobrazil, takže je to momentálne nevyužité.

Zajtra spravím merge a rovno to aj zverejním.

**Comment by mrkovec** [comment]
Super, som rad ze to slo tak hladko. 
Mas to dobre navrhnute, diki za spolupracu a mam pripravenych par dalsich hotovych veci.
