### ISSUE TITLE
'Vegan' label na 100% vegan produktoch

### ISSUE THREAD

**Issue by mrkovec** [Matoo125/Vegapo#44]
@Matoo125  spravil som jednoduchy pull pre oznacenie/zvyraznenie 100% vegan produktov - moj navrh ako by to pripadne mohlo vyzerat - kedze aj ja patrim do fundamentalistickeho tabora ;)
Pouzil som public domain logo z http://www.vegansymbol.com/ ako overlay obrazka pre 100% vegan produkty v indexe.
Je to len navrh, ak prejde, finalny dizaj necham na taba.

**Comment by Matoo125** [comment]
Pridal som boostrap badge pre každý typ.

**Comment by mrkovec** [comment]
super :+1:
