### ISSUE TITLE
Facebook login.

### ISSUE THREAD

**Issue by mrkovec** [Matoo125/Vegapo#7]
Moznost pouzit Facebook OAuth pri:
- registracii novych uzivatelov - vegapo konto sa predplni FB udajmi a naparuje na FB ucet. 
- naparovani existujuceho konta na FB ucet - udaje konta sa nemenia
- prihlasovanie uzivatelov 

Basic buttony pre oauth funkcionalitu pridane do modalnych okien pre prihlasenie a registraciu a do uzivatelskeho profilu. Dalsi dizajn nacham radsej na profika.

**Comment by Matoo125** [comment]
Pozeral som https://hybridauth.github.io/ a vyzerá to dosť dobre. Dá sa tam spraviť Facebook / Google auth spoločne. Možno by to stálo za zváženie.

**Comment by mrkovec** [comment]
Ze som na to nenarazil skor :) 
Ten FB oauth mi prisiel zvladnutelny, tak som ani nehladal nejake helpery.
Nevadi, ak by bol zaujem o dalsie moznosti prihlasovania (a teda ze ich podporuje pozehnane) nie je problem ich spristupnit pomocou tejto kniznice.

**Comment by Matoo125** [comment]
Ok, takže ty si to už spravil 😄 . Vyzerá to super, pokúsim sa spojazdniť. 

Jedine ten Google by sa teoreticky hodil, ale nieje to moc dôležité.

**Comment by Matoo125** [comment]
Takže aj to funguje dobre. 
+ Ešte by som zmenil tlačítko "connect facebook" na "disconnect facebook" alebo by som ho iba schoval pro tých, čo už sú napojený. 
+ Možno nejaká poznámka že "ak sa chcete prihlásiť pomocou emailu prosím zadajte si heslo" pre tých čo sú napojený iba na fb
+ Ak by bol niekto napojený iba na fb a chcel by disconnet, dostal by error, že si musí najprv zadať heslo.

**Comment by mrkovec** [comment]
> Ešte by som zmenil tlačítko "connect facebook" na "disconnect facebook" alebo by som ho iba schoval pro tých, čo už sú napojený.

Myslel som zeby mozno bolo dobre im to nechat, ak by si chceli connectnut ine fb konto ako uz maju. Ale je fakt, ze kolko uzivatelov by nieco take aj realne spravilo. Mozno najlepsie riesenie by bolo pridat tlacidlo disconnect (aj s tym umozornenim na nezadane heslo).
> Možno nejaká poznámka že "ak sa chcete prihlásiť pomocou emailu prosím zadajte si heslo" pre tých čo sú napojený iba na fb

Dobry napad.

**Comment by Matoo125** [comment]
Ja by som dal disconnect iba s heslom a potom si môžu znova pripojiť hocijaký účet. Zadať heslo zas tak ťažké nieje a aspoň sa nám tu neobjavia neprihlásitelné účty.

Nechám to na teba, keď tento detail doriešiš spravím merge.

**Comment by mrkovec** [comment]
Upravene. Skus pozriet.

**Comment by Matoo125** [comment]
s
